### ISSUE TITLE
KeyError: 'WERKZEUG_SERVER_FD'

### ISSUE THREAD

**Issue by stevem995** [python-microservices/pyms#241]
**Describe the bug**
main.py fails with error: 
python main.py
Traceback (most recent call last):
  File "/Users/a369505/gitwkspace/US1050985/pyms/src/main.py", line 15, in <module>
    app.run()
  File "/Users/a369505/.pyenv/versions/3.9.9/lib/python3.9/site-packages/flask/app.py", line 1188, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/Users/a369505/.pyenv/versions/3.9.9/lib/python3.9/site-packages/werkzeug/serving.py", line 1069, in run_simple
    fd = int(os.environ["WERKZEUG_SERVER_FD"])
  File "/Users/a369505/.pyenv/versions/3.9.9/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'WERKZEUG_SERVER_FD'

Unable to freeze version and get it to work. 

**To Reproduce**
1. python -m pip install py-ms[all]
2. python main.py
**Expected behavior**
Flask runs.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 12.6
 - Browser [e.g. chrome, safari] NA
 - Version [e.g. 22] NA

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] NA
 - OS: [e.g. iOS8.1] NA
 - Browser [e.g. stock browser, safari] NA
 - Version [e.g. 22] NA

**Additional context**

**Comment by krishnabhushank** [comment]
Hi. Is there any workaround for this issue.
