### ISSUE TITLE
 KeyError: 'APP_NAME', formatter.add_service_name(self.application.config["APP_NAME"])

### ISSUE THREAD

**Issue by NguyenDangBinh** [python-microservices/pyms#242]
**Describe the bug**
from pyms.flask.app import Microservice
ms = Microservice()
app = ms.create_app()
if __name__ == '__main__':
    app.run()

And I had this errors. Can I help me?
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    app = ms.create_app()
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python36\lib\site-packages\pyms\flask\app\create_app.py", line 164, in create_app
    self.init_logger()
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python36\lib\site-packages\pyms\flask\app\create_app.py", line 104, in init_logger
    formatter.add_service_name(self.application.config["APP_NAME"])
KeyError: 'APP_NAME'

**Comment by NguyenDangBinh** [comment]
dear all, 
I update the error below.
    ms = Microservice()
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python36\lib\site-packages\pyms\flask\app\utils.py", line 16, in __call__
    cls._instances[cls] = super(SingletonMeta, cls).__call__(*args, **kwargs)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python36\lib\site-packages\pyms\flask\app\create_app.py", line 47, in __init__
    validate_conf()
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python36\lib\site-packages\pyms\config\conf.py", line 44, in validate_conf
    config = ConfFile(*args, **kwargs)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python36\lib\site-packages\pyms\config\confile.py", line 60, in __init__
    raise ConfigDoesNotFoundException("Configuration file {}not found".format(path + " "))
pyms.exceptions.ConfigDoesNotFoundException: Configuration file  not found
